name: Python syntax check

on: [push, pull_request]

jobs:
  python_syntax_check:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' || 
      github.event.repository.fork == true || 
      github.ref != 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - name: Install Python dependencies
      run: python3 -m pip install --upgrade pip
    - name: Check Python syntax
      run: |
        find . -name "*.py" -print0 | while IFS= read -r -d '' file; do
          python3 -m py_compile "$file" || exit 1
        done