name: C++ Syntax Tests

on: [push, pull_request]

jobs:
  cpp_syntax_check:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' || 
      github.event.repository.fork == true || 
      github.ref != 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - name: Install C++ dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev
    - name: Check C++ syntax
      run: |
        find . -name "*.cpp" -print0 | while IFS= read -r -d '' file; do
          g++ -fsyntax-only -std=c++17 -o /dev/null -S "$file" || exit 1
        done
